### ISSUE TITLE
Static return_type

### ISSUE THREAD

**Issue by oxinabox** [oxinabox/Tricks.jl#22]
I think we can get `Core.Compiler.return_type` to work with this same trick, and the same advantages.
Though even more than usual this may be unwise, since it is 1) internal, 2) doesn't have very strictly defined behavour, 3) depending on it might be even more of an antipattern, then depending on if methods exist.

OTOH, using `return_type` more would be super useful for a bunch of things like making memoization type-stable.

**Comment by simeonschaub** [comment]
I am pretty sure it's already a tfunc, i.e.:
```julia
julia> using Test
julia> Base.return_types((Int, Float64)) do x...           Core.Compiler.return_type(+, typeof(x))
       end
1-element Vector{Any}:
 Type{Float64}
```

**Comment by oxinabox** [comment]
Hmm need to time it then

**Comment by simeonschaub** [comment]
It just constant folds, so it should be completely free at runtime:
```julia
julia> Base.code_typed((Int, Float64)) do x...
           Core.Compiler.return_type(+, typeof(x))
       end
1-element Array{Any,1}:
 CodeInfo(
1 ─     return Float64
) => Type{Float64}

julia> @btime (function (x...)
           Core.Compiler.return_type(+, typeof(x))
       end)(1, 2.)
  0.022 ns (0 allocations: 0 bytes)
Float64
```
